taxiexpress/config/routes.rb
Rails.application.routes.draw do
  
  
 
  resources :services
  resources :address_favorites
  resources :routes
  resources :routes
  resources :routes
  resources :routes
  resources :addresses
  
  devise_for :users
  
  devise_scope :user do
    
    authenticated :user do
      root :to => 'services#index'
    end
    
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
    
  end
  
  get '/finish_service', to: "services#finish_service", as: "finish_service"
  
  get 'home/login'
  get 'home/register'
  resources :operator
  resources :pasajeros
  resources :passengers
  get 'forms/form_pasajero'
  
  get 'operator/dashboard'
  get 'operator/set_driver'
  get 'operator/fin_services'
  get 'operator/prices'
  get 'operator/driver_actives'
  get 'operator/feedback'

  get 'forms/login_pasajero'

  get 'driver/dashboard'
  get 'driver/last_services'
  get 'driver/pend_services'
  get 'driver/me'
  
  get 'passenger/reserva'
  get 'passenger/rutas'
  get 'passenger/comentarios'
  get 'passenger/mapas'
  get 'home/index'
  

  
end

taxiexpress/app/models/address.rb
class Address < ActiveRecord::Base
  
  has_many :address_orgin_address, :foreign_key => "address_origin_id", :class_name => "Route"  
  has_many :address_destiny_address, :foreign_key => "address_destiny_id", :class_name => "Route"
  


end

taxiexpress/app/models/address_favorite.rb
class AddressFavorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :address
  
  validates :address_id, presence: true
end

taxiexpress/app/models/driver.rb
class Driver < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

taxiexpress/app/models/operator.rb
class Operator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

taxiexpress/app/models/passenger.rb
class Passenger < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

taxiexpress/app/models/route.rb
class Route < ActiveRecord::Base
    belongs_to :address_origin, :class_name => "Address"
    belongs_to :address_destiny, :class_name => "Address"
    
    
    public 
    def description

  	    return  self.address_origin.name << " - " << self.address_destiny.name << ": S/. " << self.price.to_s 
    end
    def description_2

  	    return  self.address_origin.name << " - " << self.address_destiny.name
    end
end

taxiexpress/app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user_driver, :class_name => "User"
  belongs_to :user_customer, :class_name => "User"
  belongs_to :route
  
  
  public 
    def full_name_customer

  	    return  self.user_customer.name  << " " << self.user_customer.last_name
    end
    
    def full_name_drive

  	    return  self.user_driver.name  << " " << self.user_driver.last_name
    end
    
    def pay_method_description
      if self.pay_method == 0
        descripcion = "Contado" 
      else 
        descripcion = "Tarjeta"
      end
        
      return descripcion
    end
      
  
end

taxiexpress/app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_driver_user, :foreign_key => "user_driver_id", :class_name => "Service"
  has_many :user_customer_user, :foreign_key => "user_customer_id", :class_name => "Service"
  
  
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
  public 
  def description_driver
    return self.name << " " << self.last_name << " - NP: " << self.num_passenger.to_s << " CT: " << self.car_type
  end
end

taxiexpress/app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def form_pasajero
  end
  def login_pasajero
    @pasajero='Pasajero_prueba'
  end
end

taxiexpress/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @project = 'Taxi-Express'
  end
  
  def login
    @dashboard = params[:type]
    @link_to_dashboard = "/#{@dashboard}/dashboard"
    @link_to_register = "/home/register?type=#{@dashboard}"
    @dashboard.upcase!
    puts ""
    
    
  end
  
  def register
    @dashboard = params[:type]
    @link_to_dashboard = "/#{@dashboard}/dashboard"
    @link_to_login = "/home/login?type=#{@dashboard}"
    @dashboard.upcase!
    puts ""
   # @nuevo_usuario_registrado=Pasajero.create({nombre_pasajero: @nombre_pasajero})
    
  end
end

taxiexpress/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
before_action :configure_devise_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!
  protected

    def configure_devise_permitted_parameters
        registration_params = [:email, :name, :last_name, :user_type, :state, :car_type, :num_passenger, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
    end
end

taxiexpress/app/helpers/addresses_helper.rb
module AddressesHelper
end

taxiexpress/app/helpers/application_helper.rb
module ApplicationHelper
end

taxiexpress/app/helpers/driver_helper.rb
module DriverHelper
end

taxiexpress/app/helpers/forms_helper.rb
module FormsHelper
end

taxiexpress/app/helpers/home_helper.rb
module HomeHelper
end

taxiexpress/app/helpers/operator_helper.rb
module OperatorHelper
end

taxiexpress/app/helpers/passenger_helper.rb
module PassengerHelper
end

taxiexpress/app/helpers/routes_helper.rb
module RoutesHelper
end

taxiexpress/app/helpers/services_helper.rb
module ServicesHelper
end

taxiexpress/app/views/layouts/application.html.bkp.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taxiexpress</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Taxi Express</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Iniciar sesion</a></li>
            <li><a href="#">Registrarse</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input class="form-control" placeholder="Search..." type="text">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid main">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>

        <div class="col-sm-9 col-md-10">
  
        <%= yield %>
    
        </div>
      </div>
    </div>

</body>
</html>

taxiexpress/app/views/layouts/application.html.erb
<html>
    <head>
        <title> Taxi Express</title>   
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
      
      
      <% if user_signed_in? %>
       
        <%= render "partials/header" %>
    
         <%= yield %>
                    </div>
                </div>              
                 <!-- /. ROW  -->
            </div>
        </div>
        </div>	
    
        <% else %>
            <%= render "partials/header_login" %>
            
             <%= yield %>       
        </div>
       	
      <% end %>
      
      
      
    </body></html>

taxiexpress/app/views/layouts/driver.html.erb
<html>
    <head>
        <title> Taxi Express</title>   
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div id="wrapper">
                    <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/driver/dashboard">Driver Dash</a> 
            </div>
  <div style="color: white;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;"> Last access : 30 May 2014 &nbsp; <a href="/" class="btn btn-danger square-btn-adjust">Logout</a> </div>
        </nav> 
        
                   <!-- /. NAV TOP  -->
                <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
        <li class="text-center">
                    <img src="https://cdn2.iconfinder.com/data/icons/large-people-svg-icons/512/driver_drives_hard_floppy-128.png" class="user-image img-responsive"/>
          </li>
        
          
                    <li>
                        <a class="active-menu"  href="/driver/dashboard"><i class="fa fa-dashboard fa-3x"></i> Dashboard</a>
                    </li>
                     <li>
                        <a  href="/driver/pend_services"><i class="fa fa-desktop fa-3x"></i> Servicios pendientes</a>
                    </li>
                    <li>
                        <a  href="/driver/last_services"><i class="fa fa-paperclip fa-3x"></i> Servicios ejecutados</a>
                    </li>
        
                  <li  >
                        <a  href="/driver/me"><i class="fa fa-user fa-3x"></i> Mis datos</a>
                    </li> 
                </ul>
               
            </div>
            
        </nav>  
                <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                    <%= yield %>
                    </div>
                </div>              
                 <!-- /. ROW  -->
            </div>
        </div>
        </div>
    </body>
</htm>

taxiexpress/app/views/layouts/forms.html.erb
<html>
    <head>
        <title> Taxi Express</title>   
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
       <form>
        <%= yield %>
        
        </form>
    </body>
</htm>

taxiexpress/app/views/layouts/home.html.erb
<html>
    <head>
        <title> Taxi Express</title>   
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        
        <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
          <span style="padding-left:10px;">
          <img class="" style="vertical-align: middle;" src="https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_local_taxi_48px-24.png"></img>
          Taxi 
          Express
          </a>
          </span>
          
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav>
    
<div class="container" style="padding-top:60px;">
        <%= yield %>       
        </div>
    </body>
</htm>

taxiexpress/app/views/layouts/operator.html.erb
<html>
    <head>
        <title> Taxi Express</title>   
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div id="wrapper">
                    <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/operator/dashboard">Operator Dash</a> 
            </div>
  <div style="color: white;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;"> Last access : 30 May 2014 &nbsp; <a href="/" class="btn btn-danger square-btn-adjust">Logout</a> </div>
        </nav> 
        
                   <!-- /. NAV TOP  -->
                <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
        <li class="text-center">
                    <img src="https://cdn4.iconfinder.com/data/icons/flat-color-icons/504/customer_support-128.png" class="user-image img-responsive"/>
          </li>
        
          
                    <li>
                        <a class="active-menu"  href="/operator/dashboard"><i class="fa fa-dashboard fa-3x"></i> Dashboard</a>
                    </li>
                     <li>
                        <a  href="/operator/set_driver"><i class="fa fa-desktop fa-3x"></i> Asignación de chofer</a>
                    </li>
                    <li>
                        <a  href="/operator/fin_services"><i class="fa fa-qrcode fa-3x"></i>Servicios realizados</a>
                    </li>
               <li  >
                        <a   href="/operator/feedback"><i class="fa fa-bar-chart-o fa-3x"></i> Feedback</a>
                    </li> 
                      <li  >
                        <a  href="/operator/driver_actives"><i class="fa fa-table fa-3x"></i> Choferes activos</a>
                    </li>
                    <li  >
                        <a  href="/operator/prices"><i class="fa fa-edit fa-3x"></i> Precios por rutas </a>
                    </li>       
          
     

                </ul>
               
            </div>
            
        </nav>  
                <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                    <%= yield %>
                    </div>
                </div>              
                 <!-- /. ROW  -->
            </div>
        </div>
        </div>
    </body>
</htm>

taxiexpress/app/views/layouts/passenger.html.erb
<html>
    <head>
        <title> Taxi Express</title>   
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div id="wrapper">
                    <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/passenger/dashboard">Pasajero</a> 
            </div>
            <div style="color: white;padding: 15px 50px 5px 50px;float: right;font-size: 16px;">
               <% if passenger_signed_in? %>
                   Bienvenido &nbsp; <%= current_passenger.email %>
                   <%= link_to "Cerrar Sesión", destroy_passenger_session_path, method: :delete, :class => "btn btn-danger square-btn-adjust" %>
               <% end %>
       </div>
        </nav> 
        
                   <!-- /. NAV TOP  -->
                <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
        <li class="text-center">
                    <img src="https://cdn0.iconfinder.com/data/icons/flat-color-icons/504/manager-128.png" class="user-image img-responsive"/>
          </li>
        
          
                    <li>
                        <a class="active-menu"  href="/passenger/dashboard"><i class="fa fa-dashboard fa-3x"></i> Dashboard</a>
                    </li>
                     <li>
                        <a  href="/passenger/reserva"><i class="fa fa-desktop fa-3x"></i> Reserva</a>
                    </li>
                    <li>
                        <a  href="/passenger/rutas"><i class="fa fa-qrcode fa-3x"></i> Rutas favoritas</a>
                    </li>
               <li  >
                        <a   href="/passenger/comentarios"><i class="fa fa-bar-chart-o fa-3x"></i> Comentarios</a>
                    </li> 
                      <li  >
                        <a  href="/passenger/mapas"><i class="fa fa-table fa-3x"></i> Google Maps</a>
                    </li>
                  
                    
                        
                        
                        
                 
                </ul>
               
            </div>
            
        </nav>  
                <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                                <p class="notice"> <%= notice %> </p>
                                <p class="alert"> <%= alert %></p>

                                <%= yield %>
                    </div>
                </div>              
                 <!-- /. ROW  -->
            </div>
        </div>

        </div>
    </body>
</htm>

taxiexpress/app/views/partials/_header.html.erb
        <div id="wrapper">
                    <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                
                <a class="navbar-brand" href="/driver/dashboard"> <%=current_user.user_type== "C" ? "Dash pasajero" : current_user.user_type=="D" ? "Taxista Dashboard" : "Dashboard operador" %></a> 
            </div>
  <div style="color: white;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;"> Last access : 30 May 2014 &nbsp; <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class:"btn btn-danger square-btn-adjust" %> </div>

        </nav> 
        
                   <!-- /. NAV TOP  -->
                <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
        <li class="text-center">
                    <img src="https://cdn2.iconfinder.com/data/icons/large-people-svg-icons/512/driver_drives_hard_floppy-128.png" class="user-image img-responsive"/>
          </li>
        
          
                    <li>
                        <a class="active-menu"  href="/driver/dashboard"><i class="fa fa-dashboard fa-3x"></i> Dashboard</a>
                    </li>
                     <li>
                        <a  href="/driver/pend_services"><i class="fa fa-desktop fa-3x"></i> Servicios pendientes</a>
                    </li>
                    <li>
                        <a  href="/driver/last_services"><i class="fa fa-paperclip fa-3x"></i> Servicios ejecutados</a>
                    </li>
        
                  <li  >
                        <a  href="/driver/me"><i class="fa fa-user fa-3x"></i> Mis datos</a>
                        
                        
                    </li> 
                    
                    
                </ul>
               
            </div>
            
        </nav>  
                <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                   
   

taxiexpress/app/views/partials/_header_login.html.erb
        <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
          <span style="padding-left:10px;">
          <img class="" style="vertical-align: middle;" src="https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_local_taxi_48px-24.png"></img>
          Taxi 
          Express
          </a>
          </span>
          
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav>
    
<div class="container" style="padding-top:60px;">