taxiexpress/config/routes.rb
Rails.application.routes.draw do
  
  
 
  resources :services
  resources :address_favorites
  resources :routes
  resources :routes
  resources :routes
  resources :routes
  resources :addresses
  
  devise_for :users
  
  devise_scope :user do
    
    authenticated :user do
      root :to => 'services#index'
    end
    
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
    
  end
  
  get '/finish_service', to: "services#finish_service", as: "finish_service"
  
  get 'home/login'
  get 'home/register'
  resources :operator
  resources :pasajeros
  resources :passengers
  get 'forms/form_pasajero'
  
  get 'operator/dashboard'
  get 'operator/set_driver'
  get 'operator/fin_services'
  get 'operator/prices'
  get 'operator/driver_actives'
  get 'operator/feedback'

  get 'forms/login_pasajero'

  get 'driver/dashboard'
  get 'driver/last_services'
  get 'driver/pend_services'
  get 'driver/me'
  
  get 'passenger/reserva'
  get 'passenger/rutas'
  get 'passenger/comentarios'
  get 'passenger/mapas'
  get 'home/index'
  

  
end

taxiexpress/app/models/address.rb
class Address < ActiveRecord::Base
  
  has_many :address_orgin_address, :foreign_key => "address_origin_id", :class_name => "Route"  
  has_many :address_destiny_address, :foreign_key => "address_destiny_id", :class_name => "Route"
  


end

taxiexpress/app/models/address_favorite.rb
class AddressFavorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :address
  
  validates :address_id, presence: true
end

taxiexpress/app/models/driver.rb
class Driver < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

taxiexpress/app/models/operator.rb
class Operator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

taxiexpress/app/models/passenger.rb
class Passenger < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

taxiexpress/app/models/route.rb
class Route < ActiveRecord::Base
    belongs_to :address_origin, :class_name => "Address"
    belongs_to :address_destiny, :class_name => "Address"
    
    
    public 
    def description

  	    return  self.address_origin.name << " - " << self.address_destiny.name << ": S/. " << self.price.to_s 
    end
    def description_2

  	    return  self.address_origin.name << " - " << self.address_destiny.name
    end
end

taxiexpress/app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user_driver, :class_name => "User"
  belongs_to :user_customer, :class_name => "User"
  belongs_to :route
  
  
  public 
    def full_name_customer

  	    return  self.user_customer.name  << " " << self.user_customer.last_name
    end
    
    def full_name_drive

  	    return  self.user_driver.name  << " " << self.user_driver.last_name
    end
    
    def pay_method_description
      if self.pay_method == 0
        descripcion = "Contado" 
      else 
        descripcion = "Tarjeta"
      end
        
      return descripcion
    end
      
  
end

taxiexpress/app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_driver_user, :foreign_key => "user_driver_id", :class_name => "Service"
  has_many :user_customer_user, :foreign_key => "user_customer_id", :class_name => "Service"
  
  
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
  public 
  def description_driver
    return self.name << " " << self.last_name << " - NP: " << self.num_passenger.to_s << " CT: " << self.car_type
  end
end

taxiexpress/app/controllers/driver_controller.rb
class DriverController < ApplicationController
  
  def dashboard
    @usuario='User_prueba'
  end
end

def pend_services
  @servicios = [ ]
end

def last_services
  @servicios = [ ]
end  


def me
  @me = {nombre=>"fredy"}
end

taxiexpress/app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def form_pasajero
  end
  def login_pasajero
    @pasajero='Pasajero_prueba'
  end
end

taxiexpress/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @project = 'Taxi-Express'
  end
  
  def login
    @dashboard = params[:type]
    @link_to_dashboard = "/#{@dashboard}/dashboard"
    @link_to_register = "/home/register?type=#{@dashboard}"
    @dashboard.upcase!
    puts ""
    
    
  end
  
  def register
    @dashboard = params[:type]
    @link_to_dashboard = "/#{@dashboard}/dashboard"
    @link_to_login = "/home/login?type=#{@dashboard}"
    @dashboard.upcase!
    puts ""
   # @nuevo_usuario_registrado=Pasajero.create({nombre_pasajero: @nombre_pasajero})
    
  end
end

taxiexpress/app/controllers/operator_controller.rb
class OperatorController < ApplicationController
  def dashboard
  end
  
  def set_driver
  end
  
  def fin_services
  end
  
  def feedback
  end
  
  def driver_actives
  end
  
  def prices
  end
end

taxiexpress/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:price)
    end
end

taxiexpress/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
before_action :configure_devise_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!
  protected

    def configure_devise_permitted_parameters
        registration_params = [:email, :name, :last_name, :user_type, :state, :car_type, :num_passenger, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
    end
end

taxiexpress/app/helpers/addresses_helper.rb
module AddressesHelper
end

taxiexpress/app/helpers/application_helper.rb
module ApplicationHelper
end

taxiexpress/app/helpers/driver_helper.rb
module DriverHelper
end

taxiexpress/app/helpers/forms_helper.rb
module FormsHelper
end

taxiexpress/app/helpers/home_helper.rb
module HomeHelper
end

taxiexpress/app/helpers/operator_helper.rb
module OperatorHelper
end

taxiexpress/app/helpers/passenger_helper.rb
module PassengerHelper
end

taxiexpress/app/helpers/routes_helper.rb
module RoutesHelper
end

taxiexpress/app/helpers/services_helper.rb
module ServicesHelper
end

taxiexpress/app/views/operator/dashboard.html.erb
 <h2>Operator Dashboard</h2>   
<h5>Welcome </h5>
<p>Find me in app/views/operator/dashboard.html.erb</p>

taxiexpress/app/views/operator/driver_actives.html.erb
<h2>Choferes activos</h2>

taxiexpress/app/views/operator/feedback.html.erb
<h2>Feedback de clientes</h2>

taxiexpress/app/views/operator/fin_services.html.erb
<h2>Servicios terminados por chofer</h2>
            
            
            <label for="seleccionar">Seleccionar chofer: </label>
            <select class="form">
                <option>Juan Perez</option>
                <option>Pedro Garcia</option>
                <option>Oscar sanz</option>
            </select>
            
            
<table class="table">
    <tr>
        <th>Fecha</th>    
        <th>Hora Solicitud</th>    
        <th>Origen</th>    
        <th>Destino</th>    
        <th>Chofer</th>    
        <th>Asignar</th>    
    </tr>

    
    <tr>
        <td>2015-09-06</td>    
        <td>08:00</td>    
        <td>origen</td>    
        <td>destino</td>    
        <td>Precio</td>    
        <td>
            Juan Perez
        </td>    
        <td><button class="btn btn-success btn-sm">Asignar</button></td>    
    </tr>

    <tr>
        <td>2015-09-06</td>    
        <td>08:00</td>    
        <td>origen</td>    
        <td>destino</td>    
        <td>Precio</td>    
        <td>
            Juan Perez
        </td>    
        <td><button class="btn btn-success btn-sm">Asignar</button></td>    
    </tr>

    <tr>
        <td>2015-09-06</td>    
        <td>08:00</td>    
        <td>origen</td>    
        <td>destino</td>    
        <td>Precio</td>    
        <td>
            Juan Perez
        </td>    
        <td><button class="btn btn-success btn-sm">Asignar</button></td>    
    </tr>

</table>

taxiexpress/app/views/operator/prices.html.erb
<h2>Precios por rutas</h2>

taxiexpress/app/views/operator/set_driver.html.erb
<h2>Asignar chofer a servicios pendientes</h2>
<table class="table">
    <tr>
        <th>Fecha</th>    
        <th>Hora Solicitud</th>    
        <th>Origen</th>    
        <th>Destino</th>    
        <th>Chofer</th>    
        <th>Asignar</th>    
    </tr>
    <tr>
        <td>2015-09-06</td>    
        <td>08:00</td>    
        <td>origen</td>    
        <td>destino</td>    
        <td>Precio</td>    
        <td>
            <select>
                <option>Juan Perez</option>
                <option>Pedro Garcia</option>
                <option>Oscar sanz</option>
            </select>
            
        </td>    
        <td><button class="btn btn-success btn-sm">Asignar</button></td>    
    </tr>
    
    <tr>
        <td>2015-09-06</td>    
        <td>08:00</td>    
        <td>origen</td>    
        <td>destino</td>    
        <td>Precio</td>    
        <td>
            <select>
                <option>Juan Perez</option>
                <option>Pedro Garcia</option>
                <option>Oscar sanz</option>
            </select>
            
        </td>    
        <td><button class="btn btn-success btn-sm">Asignar</button></td>    
    </tr>
    
    <tr>
        <td>2015-09-06</td>    
        <td>08:00</td>    
        <td>origen</td>    
        <td>destino</td>    
        <td>Precio</td>    
        <td>
            <select>
                <option>Juan Perez</option>
                <option>Pedro Garcia</option>
                <option>Oscar sanz</option>
            </select>
            
        </td>    
        <td><button class="btn btn-success btn-sm">Asignar</button></td>    
    </tr>
    
    <tr>
        <td>2015-09-06</td>    
        <td>08:00</td>    
        <td>origen</td>    
        <td>destino</td>    
        <td>Precio</td>    
        <td>
            <select>
                <option>Juan Perez</option>
                <option>Pedro Garcia</option>
                <option>Oscar sanz</option>
            </select>
            
        </td>    
        <td><button class="btn btn-success btn-sm">Asignar</button></td>    
    </tr>
    
    <tr>
        <td>2015-09-06</td>    
        <td>08:00</td>    
        <td>origen</td>    
        <td>destino</td>    
        <td>Precio</td>    
        <td>
            <select>
                <option>Juan Perez</option>
                <option>Pedro Garcia</option>
                <option>Oscar sanz</option>
            </select>
            
        </td>    
        <td><button class="btn btn-success btn-sm">Asignar</button></td>    
    </tr>
    
    <tr>
        <td>2015-09-06</td>    
        <td>08:00</td>    
        <td>origen</td>    
        <td>destino</td>    
        <td>Precio</td>    
        <td>
            <select>
                <option>Juan Perez</option>
                <option>Pedro Garcia</option>
                <option>Oscar sanz</option>
            </select>
            
        </td>    
        <td><button class="btn btn-success btn-sm">Asignar</button></td>    
    </tr>
    
    <tr>
        <td>2015-09-06</td>    
        <td>08:00</td>    
        <td>origen</td>    
        <td>destino</td>    
        <td>Precio</td>    
        <td>
            <select>
                <option>Juan Perez</option>
                <option>Pedro Garcia</option>
                <option>Oscar sanz</option>
            </select>
            
        </td>    
        <td><button class="btn btn-success btn-sm">Asignar</button></td>    
    </tr>
    
</table>

taxiexpress/app/views/routes/_form.html.erb
<%= simple_form_for(@route) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

taxiexpress/app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

taxiexpress/app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Routes</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.price %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

taxiexpress/app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

taxiexpress/app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @route.price %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>