taxiexpress/config/routes.rb
Rails.application.routes.draw do
  
  
 
  resources :services
  resources :address_favorites
  resources :routes
  resources :routes
  resources :routes
  resources :routes
  resources :addresses
  
  devise_for :users
  
  devise_scope :user do
    
    authenticated :user do
      root :to => 'services#index'
    end
    
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
    
  end
  
  get '/finish_service', to: "services#finish_service", as: "finish_service"
  
  get 'home/login'
  get 'home/register'
  resources :operator
  resources :pasajeros
  resources :passengers
  get 'forms/form_pasajero'
  
  get 'operator/dashboard'
  get 'operator/set_driver'
  get 'operator/fin_services'
  get 'operator/prices'
  get 'operator/driver_actives'
  get 'operator/feedback'

  get 'forms/login_pasajero'

  get 'driver/dashboard'
  get 'driver/last_services'
  get 'driver/pend_services'
  get 'driver/me'
  
  get 'passenger/reserva'
  get 'passenger/rutas'
  get 'passenger/comentarios'
  get 'passenger/mapas'
  get 'home/index'
  

  
end

taxiexpress/app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user_driver, :class_name => "User"
  belongs_to :user_customer, :class_name => "User"
  belongs_to :route
  
  
  public 
    def full_name_customer

  	    return  self.user_customer.name  << " " << self.user_customer.last_name
    end
    
    def full_name_drive

  	    return  self.user_driver.name  << " " << self.user_driver.last_name
    end
    
    def pay_method_description
      if self.pay_method == 0
        descripcion = "Contado" 
      else 
        descripcion = "Tarjeta"
      end
        
      return descripcion
    end
      
  
end

taxiexpress/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy, :finish_service]
  before_action :authenticate_user!
  respond_to :html,:json

  # GET /services
  # GET /services.json
  def index
    
      if (current_user.user_type == "C")
        @services = Service.where(user_customer_id: current_user.id) 
      else 
        if (current_user.user_type == "D")
          @services = Service.where(user_driver_id: current_user.id) 
        else
          @services = Service.all
        end
      end
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    @service.state = "R"
    if (current_user.user_type == "C")
      @service.user_customer_id = current_user.id
    end

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def finish
    codigo = params["format"]
    puts Service.find(codigo)
    @service = Service.find(codigo)
    @service.state = "F"
    @service.save
    if @service.update(service_params)
        format.html { redirect_to "/", notice: 'Service was finished.' }
    end
    
    redirect_to "/", notice: 'Service was finished.'
  end  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
        @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:num_passenger, :car_type, :pay_method, :state, :feedback, :route_id, :user_customer_id, :user_driver_id)
    end
end

taxiexpress/app/helpers/services_helper.rb
module ServicesHelper
end

taxiexpress/app/views/services/_form.html.erb
        
         <div class="row">
               
                <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                            </div>
                            <div class="panel-body">
                               <%= simple_form_for(@service) do |f| %>
                                <br>
                                      <% if current_user.user_type == "A" &&  @service.state == "R"%>
                                          <%= f.hidden_field :state,  :as => :hidden, :value => "S" %>
                                      <% else %>
                                          <%= f.hidden_field :state,  :as => :hidden, :value => @service.state.nil? ? 'R' : @service.state %>
                                      <% end %>
                                      <% if current_user.user_type == "A" %>
                                        <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-circle-o-notch"></i></span>
                                             <%= collection_select(:service, :user_driver_id, User.where(state: "A"), :id, :description_driver,{}, {id: "new-route"}) %>
                                        </div>
                                      <% end %>
                                        <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-circle-o-notch"></i></span>
                                             <%= collection_select(:service, :route_id, Route.all, :id, :description,{}, {id: "new-route"}) %>
                                        </div>
                                    
                                        <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-circle-o-notch"></i></span>
                                             <%= f.text_field :num_passenger, required: true, autofocus: true , class:"form-control" , placeholder:"Num Passenger"%>
                                        </div>
                                        
                                         <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-circle-o-notch"></i></span>
                                            <%= f.text_field :car_type, required: true, autofocus: true , class:"form-control" , placeholder:"Card Type"%>
                                        </div>
                                        <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-circle-o-notch"></i></span>
                                            <%= f.text_field :pay_method_description, required: true, autofocus: true , class:"form-control" , placeholder:"Pay Method"%>
                                        </div>
                                       
                                       
                                       <%= f.submit "Reserve", class:"btn btn-success" %>
                                       <%= link_to 'Back', services_path %>
                                    <% end %>
                            </div>
                           
                        </div>
                    </div>
                
                
        </div>
    

taxiexpress/app/views/services/edit.html.erb
<div class="row text-center  ">
    <div class="col-md-12">
        <br><br>
        <h2> Editing Service</h2>
         <br>
    </div>
</div>

<%= render 'form' %>

taxiexpress/app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>



<table class="table table-bordered">
  <thead>
    <tr>
      <th>Ruta</th>
      <th>Cant. Pasajeros</th>
      <th>Tipo carro</th>
      <th>Met. Pago</th>
      <th>Comentario</th>
      <th>Estado</th>
      <% if current_user.user_type != "C" %>
      <th>Cliente</td>
      <% end %>
      <th>Chofer</td>
      <th>Precio</td>
      <th colspan="4">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.route.description_2 %></td>
        <td><%= service.num_passenger %></td>
        <td><%= service.car_type %></td>
        <td><%= service.pay_method_description %></td>
        <td><%= service.feedback %></td>
        <td><%= service.state == "R" ? "Reserved" : service.state == "S" ? "Service" : "End Service"  %></td>
        <% if current_user.user_type != "C" %>
        <td>
          <%= service.full_name_customer %>
          
        </td>
        <% end %>
        
        <td>
            
        <% if service.user_driver  %>
          <%= service.user_driver.name %>
          <% else %>
          Por asignar
        <% end %>
        
        </td>
        
        <td>
          <%= service.route.price %>
        </td>
          
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'to Finish', finish_service_path(service) %></td>
        <td>
           <% if current_user.user_type != "D" %>
          <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.user_type == "C" %>
<%= link_to 'New Service', new_service_path %>
 <% end %>

taxiexpress/app/views/services/new.html.erb
<div class="row text-center  ">
    <div class="col-md-12">
        <br><br>
        <h2> New Services</h2>
         <br>
    </div>
</div>

<%= render 'form' %>

taxiexpress/app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num passenger:</strong>
  <%= @service.num_passenger %>
</p>

<p>
  <strong>Car type:</strong>
  <%= @service.car_type %>
</p>

<p>
  <strong>Pay method:</strong>
  <%= @service.pay_method %>
</p>

<p>
  <strong>State:</strong>
  <%= @service.state == "R" ? "Reserved" : @service.state == "S" ? "Service" : "End Service"  %>
</p>



<p>
  <strong>Route:</strong>
    <%= @service.route.description %>
</p>

<% if current_user.user_type != "C" %>
<p>
  <strong>User customer:</strong>
  <%= @service.full_name_customer %>
</p>
<% end %>

<p>
  <strong>User driver:</strong>
  <%= @service.state == "R" ? "" : @service.full_name_drive %>
</p>

<p>
  <strong>Feedback:</strong>
  <%= @service.feedback %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>