taxiexpress/config/routes.rb
Rails.application.routes.draw do
  
  
 
  resources :services
  resources :address_favorites
  resources :routes
  resources :routes
  resources :routes
  resources :routes
  resources :addresses
  
  devise_for :users
  
  devise_scope :user do
    
    authenticated :user do
      root :to => 'services#index'
    end
    
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
    
  end
  
  get '/finish_service', to: "services#finish_service", as: "finish_service"
  
  get 'home/login'
  get 'home/register'
  resources :operator
  resources :pasajeros
  resources :passengers
  get 'forms/form_pasajero'
  
  get 'operator/dashboard'
  get 'operator/set_driver'
  get 'operator/fin_services'
  get 'operator/prices'
  get 'operator/driver_actives'
  get 'operator/feedback'

  get 'forms/login_pasajero'

  get 'driver/dashboard'
  get 'driver/last_services'
  get 'driver/pend_services'
  get 'driver/me'
  
  get 'passenger/reserva'
  get 'passenger/rutas'
  get 'passenger/comentarios'
  get 'passenger/mapas'
  get 'home/index'
  

  
end

taxiexpress/app/models/address_favorite.rb
class AddressFavorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :address
  
  validates :address_id, presence: true
end

taxiexpress/app/controllers/address_favorites_controller.rb
class AddressFavoritesController < ApplicationController
  before_action :set_address_favorite, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /address_favorites
  # GET /address_favorites.json
  def index
    @address_favorites = AddressFavorite.all
  end

  # GET /address_favorites/1
  # GET /address_favorites/1.json
  def show
  end

  # GET /address_favorites/new
  def new
    @address_favorite = AddressFavorite.new
  end

  # GET /address_favorites/1/edit
  def edit
  end

  # POST /address_favorites
  # POST /address_favorites.json
  def create
      @address_favorite = AddressFavorite.new(address_favorite_params)
    
     if (current_user.user_type == "C")
        @address_favorite.user_id = current_user.id
     end

    respond_to do |format|
      if @address_favorite.save
        format.html { redirect_to @address_favorite, notice: 'Address favorite was successfully created.' }
        format.json { render :show, status: :created, location: @address_favorite }
      else
        format.html { render :new }
        format.json { render json: @address_favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /address_favorites/1
  # PATCH/PUT /address_favorites/1.json
  def update
    respond_to do |format|
      if @address_favorite.update(address_favorite_params)
        format.html { redirect_to @address_favorite, notice: 'Address favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @address_favorite }
      else
        format.html { render :edit }
        format.json { render json: @address_favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /address_favorites/1
  # DELETE /address_favorites/1.json
  def destroy
    @address_favorite.destroy
    respond_to do |format|
      format.html { redirect_to address_favorites_url, notice: 'Address favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address_favorite
      @address_favorite = AddressFavorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_favorite_params
      params.require(:address_favorite).permit(:name, :user_id, :address_id)
    end
end

taxiexpress/app/helpers/address_favorites_helper.rb
module AddressFavoritesHelper
end

taxiexpress/app/views/address_favorites/_form.html.erb
        <div class="row text-center  ">
            <div class="col-md-12">
                <br><br>
                <h2> Añadir dirección favorita?</h2>
                 <br>
            </div>
        </div>
         <div class="row">
               
                <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                            </div>
                            <div class="panel-body">
                               <%= simple_form_for(@address_favorite) do |f| %>
                                <br>
                                       
                                        <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-circle-o-notch"></i></span>
                                             
                                            
                                                 <%= f.input :name ,required: true,class:"form-control" , placeholder:"Enter nombre" %>
                                        </div>
                                        
                                         <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-circle-o-notch"></i></span>
                                            
                                            <%= f.association :address, required: true,  class:"form-control"%>
                                        </div>
 
                                        <%= f.button :submit , class:"btn btn-success" %>
                                    <% end %>
                            </div>
                           
                        </div>
                    </div>
                
                
        </div>

taxiexpress/app/views/address_favorites/edit.html.erb
<h1>Editing Address Favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @address_favorite %> |
<%= link_to 'Back', address_favorites_path %>

taxiexpress/app/views/address_favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Address Favorites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @address_favorites.each do |address_favorite| %>
      <tr>
        <td><%= address_favorite.name %></td>
        <td><%= address_favorite.user %></td>
        <td><%= address_favorite.address %></td>
        <td><%= link_to 'Show', address_favorite %></td>
        <td><%= link_to 'Edit', edit_address_favorite_path(address_favorite) %></td>
        <td><%= link_to 'Destroy', address_favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address favorite', new_address_favorite_path %>

taxiexpress/app/views/address_favorites/new.html.erb
<h1>Nueva dirección favorita</h1>

<%= render 'form' %>

<%= link_to 'Atrás', address_favorites_path %>


 
 

taxiexpress/app/views/address_favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @address_favorite.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @address_favorite.user %>
</p>

<p>
  <strong>Address:</strong>
  <%= @address_favorite.address %>
</p>

<%= link_to 'Edit', edit_address_favorite_path(@address_favorite) %> |
<%= link_to 'Back', address_favorites_path %>